# -*- coding: utf-8 -*-
"""R2Net Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iNIeCKt4MK9eEsnYw-H77OXPFA8HoYG6
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, Dataset

# Define a custom dataset class
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_length, pred_length=1):
        self.data = data
        self.seq_length = seq_length
        self.pred_length = pred_length

    def __len__(self):
        return len(self.data) - self.seq_length - self.pred_length + 1

    def __getitem__(self, idx):
        x = self.data[idx:idx + self.seq_length]
        y = self.data[idx + self.seq_length:idx + self.seq_length + self.pred_length]
        return x, y

# --- Data Loading & Preprocessing ---
data = pd.read_csv('ETTm1.csv') # Change your datasets
data = data[['date', 'OT']].copy()
data['date'] = pd.to_datetime(data['date'], format='mixed')
data.set_index('date', inplace=True)

# Normalize the ETT dataset
scaler = StandardScaler()
data['OT'] = scaler.fit_transform(data[['OT']])

# --- TRAIN-TEST SPLIT (Sequential) ---
# For time series, we take the earlier portion for training and later for testing
train_ratio = 0.8
train_size = int(len(data) * train_ratio)

train_data = data.values[:train_size]
test_data = data.values[train_size:]

# Parameters
seq_length = 96
prediction_length = 96
input_dim = 1
hidden_dim = 2
num_residual_blocks = 2
bottleneck_dim = 2

# Prepare Datasets and DataLoaders
train_dataset = TimeSeriesDataset(train_data, seq_length, pred_length=prediction_length)
test_dataset = TimeSeriesDataset(test_data, seq_length, pred_length=prediction_length)

# shuffle=True is okay for training batches, but we do not shuffle the test set
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# --- Model Definitions (Unchanged logic) ---
class GRUResidualBlock(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super(GRUResidualBlock, self).__init__()
        self.gru = nn.GRU(input_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        residual = x
        out, _ = self.gru(x)
        out = self.fc(out)
        return residual + out

class GRUBottleneckBlock(nn.Module):
    def __init__(self, input_dim, hidden_dim, bottleneck_dim):
        super(GRUBottleneckBlock, self).__init__()
        self.gru1 = nn.GRU(input_dim, bottleneck_dim, batch_first=True)
        self.gru2 = nn.GRU(bottleneck_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        residual = x
        out, _ = self.gru1(x)
        out, _ = self.gru2(out)
        out = self.fc(out)
        return residual + out

class ResNetGRU(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_residual_blocks, bottleneck_dim, prediction_length=1):
        super(ResNetGRU, self).__init__()
        self.input_dim = input_dim
        self.prediction_length = prediction_length
        self.input_layer = nn.Linear(input_dim, hidden_dim)
        self.residual_blocks = nn.ModuleList([GRUResidualBlock(hidden_dim, hidden_dim) for _ in range(num_residual_blocks // 2)])
        self.bottleneck_blocks = nn.ModuleList([GRUBottleneckBlock(hidden_dim, hidden_dim, bottleneck_dim) for _ in range(num_residual_blocks // 2)])
        self.output_layer = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        x = self.input_layer(x)
        for block in self.residual_blocks: x = block(x)
        for block in self.bottleneck_blocks: x = block(x)
        x = self.output_layer(x)
        batch_size, seq_len, _ = x.size()
        x = x.view(batch_size, seq_len * self.input_dim)
        x = x[:, :self.prediction_length * self.input_dim]
        return x.view(batch_size, self.prediction_length, self.input_dim)

# --- Training & Evaluation Execution ---
model = ResNetGRU(input_dim, hidden_dim, num_residual_blocks, bottleneck_dim, prediction_length)
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

def train_model(model, loader, criterion, optimizer, num_epochs=20):
    model.train()
    for epoch in range(num_epochs):
        epoch_loss = 0
        for inputs, targets in loader:
            inputs, targets = inputs.float(), targets.float()
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        print(f"Epoch [{epoch + 1}/{num_epochs}], Training Loss: {epoch_loss / len(loader):.4f}")

def evaluate_model(model, loader, criterion):
    model.eval()
    mse, mae = 0.0, 0.0
    with torch.no_grad():
        for inputs, targets in loader:
            inputs, targets = inputs.float(), targets.float()
            outputs = model(inputs)
            mse += criterion(outputs, targets).item()
            mae += torch.mean(torch.abs(outputs - targets)).item()
    return mse / len(loader), mae / len(loader)

# Run Training on train_loader
train_model(model, train_loader, criterion, optimizer, num_epochs=50)

# Evaluate on test_loader
mse, mae = evaluate_model(model, test_loader, criterion)
print(f"\nFinal Test Results -> MSE: {mse:.4f}, MAE: {mae:.4f}")