# -*- coding: utf-8 -*-
"""GRU_Resnet_ETTm1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17b7VCCvT1WijZAa9eMkQR3auqF1ejxeo
"""

from google.colab import drive
drive.mount('/content/drive')

import os
#os.chdir(r"/content/drive/My Drive")
os.chdir(r"Type your path here")

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from torch.utils.data import DataLoader, Dataset

# Define a custom dataset class that handles variable prediction lengths
class TimeSeriesDataset(Dataset):
    def __init__(self, data, seq_length, pred_length=1):
        self.data = data
        self.seq_length = seq_length
        self.pred_length = pred_length

    def __len__(self):
        return len(self.data) - self.seq_length - self.pred_length + 1

    def __getitem__(self, idx):
        x = self.data[idx:idx + self.seq_length]
        y = self.data[idx + self.seq_length:idx + self.seq_length + self.pred_length]
        return x, y

# Load the Weather dataset (you can uncomment and adjust the dataset loading section as needed)
#data = pd.read_csv('mpi_roof.csv', encoding='ISO-8859-1')
#data = data[['Date Time', 'CO2 (ppm)']]  # Use the target column 'CO2 (ppm)'
#data['Date Time'] = pd.to_datetime(data['Date Time'], format='mixed')
#data.set_index('Date Time', inplace=True)

# Load the Exchange Rate dataset
#data = pd.read_csv('exchange_rate.csv')
#data = data[['date', 'OT']].copy()  # Assuming 'OT' is the target variable
#data['date'] = pd.to_datetime(data['date'], format='mixed')
#data.set_index('date', inplace=True)

# Load ETTh dataset
data = pd.read_csv('ETTm1.csv')
data = data[['date', 'OT']].copy()  # Assuming 'OT' is the target variable
data['date'] = pd.to_datetime(data['date'], format='mixed')
data.set_index('date', inplace=True)

# Load Energy dataset
#data = pd.read_csv('energydata_complete.csv')
#data = data[['date', 'RH_out']]  # Use the target column 'RH Out'
#data['date'] = pd.to_datetime(data['date'],format='mixed')
#data.set_index('date', inplace=True)

# Load the Weather dataset
#data = pd.read_csv('mpi_roof.csv',encoding='ISO-8859-1')
#data = data[['Date Time', 'CO2 (ppm)']]  # Use the target column 'AQI'
#data['Date Time'] = pd.to_datetime(data['Date Time'],format='mixed')
#data.set_index('Date Time', inplace=True)

# Normalize data Weather dataset
#scaler = StandardScaler()
#data['CO2 (ppm)'] = scaler.fit_transform(data[['CO2 (ppm)']])

# Normalize the ETT dataset
scaler = StandardScaler()
data['OT'] = scaler.fit_transform(data[['OT']])

# Normalize data the Energy dataset
#scaler = StandardScaler()
#data['RH_out'] = scaler.fit_transform(data[['RH_out']])

# Normalize the exchangerate dataset
#scaler = StandardScaler()
#data['OT'] = scaler.fit_transform(data[['OT']])

# Normalize the Weather dataset
#scaler = StandardScaler()
#data['CO2 (ppm)'] = scaler.fit_transform(data[['CO2 (ppm)']])

# Define model parameters
seq_length = 96  # Sequence length for the input
prediction_length = 96  # Experiment with different prediction lengths
input_dim = 1  # Number of features in the dataset (e.g., 'CO2 (ppm)')
hidden_dim = 2
num_residual_blocks = 2
bottleneck_dim = 2

# Prepare the dataset
dataset = TimeSeriesDataset(data.values, seq_length, pred_length=prediction_length)
dataloader = DataLoader(dataset, batch_size=32, shuffle=True)

# Define the GRUResidualBlock with skip connections
class GRUResidualBlock(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super(GRUResidualBlock, self).__init__()
        self.gru = nn.GRU(input_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        residual = x  # Save the input for the skip connection
        out, _ = self.gru(x)
        out = self.fc(out)
        return residual + out  # Add the skip connection

# Define the GRUBottleneckBlock with skip connections
class GRUBottleneckBlock(nn.Module):
    def __init__(self, input_dim, hidden_dim, bottleneck_dim):
        super(GRUBottleneckBlock, self).__init__()
        self.gru1 = nn.GRU(input_dim, bottleneck_dim, batch_first=True)
        self.gru2 = nn.GRU(bottleneck_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        residual = x  # Save the input for the skip connection
        out, _ = self.gru1(x)
        out, _ = self.gru2(out)
        out = self.fc(out)
        return residual + out  # Add the skip connection

# Define the ResNetGRU model with skip connections and bottleneck blocks
class ResNetGRU(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_residual_blocks, bottleneck_dim, prediction_length=1):
        super(ResNetGRU, self).__init__()
        self.input_dim = input_dim  # Initialize input_dim as an attribute
        self.prediction_length = prediction_length  # Initialize prediction_length as an attribute
        self.input_layer = nn.Linear(input_dim, hidden_dim)
        self.residual_blocks = nn.ModuleList([GRUResidualBlock(hidden_dim, hidden_dim) for _ in range(num_residual_blocks // 2)])
        self.bottleneck_blocks = nn.ModuleList([GRUBottleneckBlock(hidden_dim, hidden_dim, bottleneck_dim) for _ in range(num_residual_blocks // 2)])
        self.output_layer = nn.Linear(hidden_dim, input_dim)

    def forward(self, x):
        x = self.input_layer(x)
        for block in self.residual_blocks:
            x = block(x)
        for block in self.bottleneck_blocks:
            x = block(x)

        # Apply the output layer
        x = self.output_layer(x)

        # Reshape to match the prediction length
        batch_size, seq_len, _ = x.size()
        x = x.view(batch_size, seq_len * self.input_dim)
        x = x[:, :self.prediction_length * self.input_dim]  # Only take the first `prediction_length` * `input_dim` elements

        # Reshape back to (batch_size, prediction_length, input_dim)
        x = x.view(batch_size, self.prediction_length, self.input_dim)

        return x


# Instantiate the model with the specified prediction length
model = ResNetGRU(input_dim, hidden_dim, num_residual_blocks, bottleneck_dim, prediction_length)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training function
def train_model(model, dataloader, criterion, optimizer, num_epochs=50):
    model.train()
    for epoch in range(num_epochs):
        epoch_loss = 0
        for inputs, targets in dataloader:
            inputs, targets = inputs.float(), targets.float()
            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        print(f"Epoch [{epoch + 1}/{num_epochs}], Loss: {epoch_loss / len(dataloader):.4f}")

# Train the model
train_model(model, dataloader, criterion, optimizer, num_epochs=50)

# Evaluation function
def evaluate_model(model, dataloader, criterion):
    model.eval()
    mse, mae = 0.0, 0.0
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs, targets = inputs.float(), targets.float()
            outputs = model(inputs)
            mse += criterion(outputs, targets).item()
            mae += torch.mean(torch.abs(outputs - targets)).item()
    mse /= len(dataloader)
    mae /= len(dataloader)
    return mse, mae

# Evaluate the model
mse, mae = evaluate_model(model, dataloader, criterion)
print(f"MSE: {mse:.4f}, MAE: {mae:.4f}")

# Save the model
# torch.save(model.state_dict(), 'resnet_gru_model.pth')