# -*- coding: utf-8 -*-
"""Time-GARN Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZP0WSpHi0yY4MM9CEexdGvEaIgADsVf
"""

# With MSE MAE MAPE RSE Dataframe Gradio
# ==============================================================================
# 0. Initial Setup for Google Colab
# ==============================================================================
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from scipy.stats import pearsonr # For Pearson Correlation
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import joblib # For saving/loading scalers

# Gradio imports (will be installed if not present)
try:
    import gradio as gr
except ImportError:
    print("Gradio not found. Installing Gradio...")
    !pip install gradio -q
    import gradio as gr
    print("Gradio installed.")

# For Google Colab: Mount Google Drive to access your data
try:
    from google.colab import drive
    drive.mount('/content/drive')
    print("Google Drive mounted successfully.")
    # Define a base path for your data and saved models
    BASE_PATH = '' # path in your Drive
    os.makedirs(BASE_PATH, exist_ok=True) # Create the directory if it doesn't exist

    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'ETTh2.csv') #ETT datasets
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'electricity.csv') #Electricity datasets
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'weather.csv') #Weather datasets
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'METR-LA.csv') #METR-LA
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'PEMS-BAY.csv') #PemsBay
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'ECL.csv') #ECL
    # ETT_DATA_PATH = os.path.join(BASE_PATH, 'energy.csv') #Energy
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'exchange_rate.csv') #Exchange_rate
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'NASDAQ_100.csv') #Nasdaq-100
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'national_illness.csv') #National Ilnes
    ETT_DATA_PATH = os.path.join(BASE_PATH, 'AQI Shanghai.csv') #AQI Shanghai
    MODEL_SAVE_PATH = os.path.join(BASE_PATH, 'custom_rnn_model.pth')
    SCALER_X_PATH = os.path.join(BASE_PATH, 'scaler_x.pkl')
    SCALER_EX_PATH = os.path.join(BASE_PATH, 'scaler_ex.pkl')
    SCALER_TARGET_PATH = os.path.join(BASE_PATH, 'scaler_target.pkl')

    print(f"Project files will be saved/loaded from: {BASE_PATH}")
    print(f"Please ensure {os.path.basename(ETT_DATA_PATH)} is uploaded to {BASE_PATH}")

except ImportError:
    print("Not in Google Colab environment. Skipping Google Drive mount.")
    BASE_PATH = './'
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'ETTh2.csv') #ETT datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'electricity.csv') #Electricity datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'weather.csv') #Weather datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'METR-LA.csv') #METR-LA datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'PEMS-BAY.csv') #PemsBay datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'ECL.csv') #ECL datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'energy.csv') #Energy datasets
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'exchange_rate.csv') #Exchange_rate
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'NASDAQ_100.csv') #Nasdaq-100
    #ETT_DATA_PATH = os.path.join(BASE_PATH, 'national_illness.csv') #National Ilnes
    ETT_DATA_PATH = os.path.join(BASE_PATH, 'AQI Shanghai.csv') #AQI Shanghai
    MODEL_SAVE_PATH = os.path.join(BASE_PATH, 'custom_rnn_model.pth')
    SCALER_X_PATH = os.path.join(BASE_PATH, 'scaler_x.pkl')
    SCALER_EX_PATH = os.path.join(BASE_PATH, 'scaler_ex.pkl')
    SCALER_TARGET_PATH = os.path.join(BASE_PATH, 'scaler_target.pkl')
    print(f"Project files will be saved/loaded from: {BASE_PATH}")
    print("Make sure your  dataset CSV file is in the same directory.")

# Set device for training (GPU if available, else CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ==============================================================================
# 1. Configuration Parameters
# ==============================================================================
# --- Time Series Specific Parameters ---
SEQUENCE_LENGTH = 30  # Number of past time steps to look at (seq_len)
PREDICTION_LENGTH = 60 # Number of future time steps to predict (pred_len)

# --- Feature Selection Parameters ---
FEATURE_SELECTION_METHOD = 'pearson' # Options: 'pearson'
NUM_EXTERNAL_FEATURES = 2            # Number of top external features to select

# --- Model Hyperparameters (These will be updated after data loading) ---
INPUT_SIZE = None       # Will be determined by the number of features in Xt
HIDDEN_SIZE = 64        # Dimension of the hidden state and cell state
EXTERNAL_VAR_SIZE = None # Will be determined by the number of features in Ex
OUTPUT_DIM = None       # Will be determined by the number of target features to predict

# --- Training Parameters ---
BATCH_SIZE = 32
NUM_EPOCHS = 50
LEARNING_RATE = 0.001

# ==============================================================================
# 2. Custom Recurrent Cell Definition
#
# ==============================================================================
class CustomRecurrentCell(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, external_var_size: int):
        super(CustomRecurrentCell, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.external_var_size = external_var_size

        # --- Parameters for Input Gate ---
        # It = sigmoid(Wx * Xt + Wh * Ht-1 + b_It)
        self.linear_x_to_it = nn.Linear(self.input_size, self.hidden_size)
        self.linear_h_to_it = nn.Linear(self.hidden_size, self.hidden_size)

        # --- Parameters for Ratio Gate ---
        # Rt = sigmoid(W_It * It / (W_Ex * Ex + epsilon) + b_Rt)
        self.linear_it_to_rt_numerator = nn.Linear(self.hidden_size, self.hidden_size)
        self.linear_ex_to_rt_denominator = nn.Linear(self.external_var_size, self.hidden_size)
        self.epsilon = 1e-8 # Small value for numerical stability in division

        # --- Parameters for Attention Gate ---
        # Query: Rt, Key/Value: Ex
        self.query_transform = nn.Linear(self.hidden_size, self.hidden_size) # Transforms Rt to query
        self.key_transform = nn.Linear(self.external_var_size, self.hidden_size)   # Transforms Ex to key
        self.value_transform = nn.Linear(self.external_var_size, self.hidden_size) # Transforms Ex to value for output

        # For scaled dot-product attention
        self.scale_factor = torch.sqrt(torch.tensor(self.hidden_size, dtype=torch.float32))

    def forward(self, x_t: torch.Tensor, h_prev: torch.Tensor, ex_t: torch.Tensor):
        """
        Forward pass for the custom recurrent cell.

        Args:
            x_t (torch.Tensor): Current input features (Xt). Shape: (batch_size, input_size)
            h_prev (torch.Tensor): Previous hidden state (Ht-1). Shape: (batch_size, hidden_size)
            ex_t (torch.Tensor): External variable (Ex). Shape: (batch_size, external_var_size)

        Returns:
            torch.Tensor: New hidden state (H_t). Shape: (batch_size, hidden_size)
        """
        # 1. Input Gate (It)
        it_output = torch.sigmoid(self.linear_x_to_it(x_t) + self.linear_h_to_it(h_prev))

        # 2. Ratio Gate (Rt)
        it_transformed = self.linear_it_to_rt_numerator(it_output)
        ex_transformed_for_ratio = self.linear_ex_to_rt_denominator(ex_t)

        numerator = it_transformed
        denominator = ex_transformed_for_ratio

        ratio_term = numerator / (denominator + self.epsilon)
        rt_output = torch.sigmoid(ratio_term)

        # 3. Attention Gate
        Q = self.query_transform(rt_output)
        K = self.key_transform(ex_t)
        V = self.value_transform(ex_t)

        # Scaled dot-product attention for single query/key/value vectors
        scores = torch.sum(Q * K, dim=1, keepdim=True) / self.scale_factor
        attention_weights = torch.softmax(scores, dim=1) # (batch_size, 1)

        best_ratio = attention_weights * V

        # 4. Final Output (New Ht-1 -> H_t)
        h_curr = best_ratio * self.value_transform(ex_t)

        return h_curr

# ==============================================================================
# 3. Custom RNN Model for Prediction
# ==============================================================================
class CustomRNNForPrediction(nn.Module):
    def __init__(self, input_size, hidden_size, external_var_size,
                 output_dim, pred_len):
        super().__init__()
        self.hidden_size = hidden_size
        self.pred_len = pred_len
        self.output_dim = output_dim

        self.cell = CustomRecurrentCell(input_size, hidden_size, external_var_size)

        # Output layer to map the final hidden state to the desired prediction length and dimensions
        self.prediction_layer = nn.Linear(self.hidden_size, self.pred_len * self.output_dim)

    def forward(self, inputs, external_vars, initial_h=None):
        # inputs: (batch_size, seq_len, input_size)
        # external_vars: (batch_size, seq_len, external_var_size)

        batch_size, seq_len, _ = inputs.size()

        if initial_h is None:
            initial_h = torch.zeros(batch_size, self.hidden_size, device=inputs.device)

        h_curr = initial_h

        # Process the input sequence using the custom cell
        for t in range(seq_len):
            x_t = inputs[:, t, :]
            ex_t = external_vars[:, t, :]
            h_curr = self.cell(x_t, h_curr, ex_t)

        # Use the final hidden state to make predictions for the entire prediction horizon
        predictions = self.prediction_layer(h_curr) # (batch_size, pred_len * output_dim)
        predictions = predictions.view(batch_size, self.pred_len, self.output_dim) # Reshape

        return predictions

# ==============================================================================
# 4. Dataset and Preprocessing
# ==============================================================================
class ETTDataset(Dataset):
    def __init__(self, df, seq_len, pred_len, features_col, external_col, target_col):
        self.seq_len = seq_len
        self.pred_len = pred_len
        self.features_col = features_col
        self.external_col = external_col
        self.target_col = target_col

        # Convert dataframe to numpy array for easier slicing
        self.data = df[features_col].values
        self.external_data = df[external_col].values if isinstance(external_col, list) else df[[external_col]].values
        self.target_data = df[target_col].values if isinstance(target_col, list) else df[[target_col]].values

        self.num_samples = len(self.data) - self.seq_len - self.pred_len + 1

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        input_seq = self.data[idx : idx + self.seq_len]
        external_seq_input = self.external_data[idx : idx + self.seq_len]
        target_seq = self.target_data[idx + self.seq_len : idx + self.seq_len + self.pred_len]

        return (
            torch.tensor(input_seq, dtype=torch.float32),
            torch.tensor(external_seq_input, dtype=torch.float32),
            torch.tensor(target_seq, dtype=torch.float32)
        )

# ==============================================================================
# 5. Feature Selection Function
# ==============================================================================
def select_external_features(df, target_col, all_features_except_target, method='pearson', num_features=1):
    """
    Selects external features based on the specified method.

    Args:
        df (pd.DataFrame): The full DataFrame including target and all candidate features.
        target_col (str or list): The name(s) of the target column(s).
        all_features_except_target (list): List of all candidate feature column names.
        method (str): 'pearson' (for Pearson Correlation).
        num_features (int): The number of top features to select.

    Returns:
        list: A list of selected external feature column names.
    """
    if not isinstance(target_col, list):
        target_col_name = target_col
    else: # If multiple targets, pick the first one for correlation for simplicity
        target_col_name = target_col[0]
        print(f"Warning: Multiple target columns provided. Using '{target_col_name}' for feature selection.")


    candidate_df = df[all_features_except_target]
    target_series = df[target_col_name]

    if method == 'pearson':
        print(f"Selecting {num_features} external features using Pearson Correlation...")
        correlations = {}
        for feature in candidate_df.columns:
            # Calculate absolute Pearson correlation coefficient
            corr, _ = pearsonr(candidate_df[feature], target_series)
            correlations[feature] = abs(corr)

        # Sort features by absolute correlation in descending order
        sorted_features = sorted(correlations.items(), key=lambda item: item[1], reverse=True)
        selected_features = [feature for feature, corr in sorted_features[:num_features]]
        print(f"Top {num_features} Pearson-correlated features: {selected_features}")
        return selected_features
    elif method == 'granger':
        print("Granger Causality is a more complex method and requires statistical tests (e.g., using statsmodels).")
        print("It often involves checking for stationarity and interpreting p-values, which is beyond this automated selection.")
        print("For a full implementation, typically iterate through features and perform:")
        print("  from statsmodels.tsa.stattools import grangercausalitytests")
        print("  test_result = grangercausalitytests(df[[feature, target_col_name]], maxlag=[lag_value], verbose=False)")
        print("Consider manual selection or a dedicated library for robust Granger causality feature selection.")
        print(f"Returning the first {num_features} features from candidates as a placeholder.")
        return all_features_except_target[:num_features]
    else:
        raise ValueError(f"Unknown feature selection method: {method}. Supported methods: ['pearson']")


# ==============================================================================
# 7. Metric Calculation Functions
# ==============================================================================
def calculate_metrics(y_true, y_pred, epsilon=1e-8):
    """
    Calculates various time series prediction metrics.

    Args:
        y_true (np.array): Ground truth values (original scale). Shape: (N_samples, pred_len, output_dim)
        y_pred (np.array): Predicted values (original scale). Shape: (N_samples, pred_len, output_dim)
        epsilon (float): Small value for numerical stability (e.g., in MAPE denominator).

    Returns:
        dict: A dictionary containing MSE, MAE, RSE, MAPE, and CORR.
    """
    # Flatten the arrays to compute metrics across all points/dimensions
    y_true_flat = y_true.flatten()
    y_pred_flat = y_pred.flatten()

    # MSE (Mean Squared Error)
    mse = mean_squared_error(y_true_flat, y_pred_flat)

    # MAE (Mean Absolute Error)
    mae = mean_absolute_error(y_true_flat, y_pred_flat)

    # RSE (Relative Squared Error)
    sum_squared_error = np.sum((y_true_flat - y_pred_flat)**2)
    sum_squared_total = np.sum((y_true_flat - np.mean(y_true_flat))**2)

    rse = np.sqrt(sum_squared_error / (sum_squared_total + epsilon))

    # MAPE (Mean Absolute Percentage Error)
    mape = np.mean(np.abs((y_true_flat - y_pred_flat) / (y_true_flat + epsilon))) * 100

    # CORR (Pearson Correlation Coefficient)
    corr_coeff, _ = pearsonr(y_true_flat, y_pred_flat)
    if np.isnan(corr_coeff): # Handle cases where std dev is zero
        corr_coeff = 0.0

    return {
        'MSE': mse,
        'MAE': mae,
        'RSE': rse,
        'MAPE': mape,
        'CORR': corr_coeff
    }


# ==============================================================================
# 8. Main Execution Block for Data Loading, Training, Evaluation, and Visualization
# ==============================================================================
if __name__ == "__main__":
    print("\n--- Starting Data Loading and Preprocessing ---")

    df = None
    try:
        df = pd.read_csv(ETT_DATA_PATH, parse_dates=['date'])
        print(f"Successfully loaded data from {ETT_DATA_PATH}")
    except FileNotFoundError:
        print(f"ERROR: ETT dataset not found at {ETT_DATA_PATH}. ")
        print("Please upload ETTh1.csv (or similar) to your Google Drive and update ETT_DATA_PATH.")
        print("Creating dummy dataframe for demonstration purposes...")
        data = {
            'date': pd.to_datetime(pd.date_range(start='2020-01-01', periods=500, freq='H')),
            'HUFL': np.random.rand(500) * 50,
            'HULL': np.random.rand(500) * 60,
            'MUFL': np.random.rand(500) * 40,
            'MULL': np.random.rand(500) * 55,
            'LUFL': np.random.rand(500) * 30,
            'LULL': np.random.rand(500) * 45,
            'OT': np.random.rand(500) * 100 # Primary target feature
        }
        df = pd.DataFrame(data)
        print("Using dummy data. Real ETT data should have more samples.")

    # 1. Feature Selection and Update Global Sizes
    # ETT dataset typically has 'OT' as the target (Oil Temperature).
    # Other features like 'HUFL', 'HULL', etc. are good for Xt.
    #target_feature_list = ['OT'] # Predicting only 'OT' for simplicity. {ETT/Electricity/Weather/Ilnes}
    #target_feature_list = ['769373'] # {Metr-LA}
    #target_feature_list = ['414694'] # {PemsBay}
    #target_feature_list = ['MT_000'] # {ECL}
    #target_feature_list = ['RH_out'] # {Energy}
    #target_feature_list = ['OT'] # {Exchange Rate}
    #target_feature_list = ['Close/Last'] # {Nasdaq-100}
    target_feature_list = ['AQI'] # {AQI Shanghai}

    # Candidate features for Xt (all numerical features except date and target)
    all_candidate_features_for_Xt = [col for col in df.columns if col not in ['date'] + target_feature_list]

    # Select external features using the defined method
    external_features = select_external_features(
        df,
        target_col=target_feature_list,
        all_features_except_target=all_candidate_features_for_Xt,
        method=FEATURE_SELECTION_METHOD,
        num_features=NUM_EXTERNAL_FEATURES
    )

    # Now define `all_features` (for Xt) to include everything but date and target
    all_features = all_candidate_features_for_Xt + target_feature_list # Include target for scaling consistency.
    # Re-evaluate all_features to be truly the input features for Xt
    # For Xt, it's typically all features *before* the target is removed for the output.
    # Let's consider `all_features` to be all features that describe `Xt` at any time step.
    all_features_for_Xt_input = [col for col in df.columns if col not in ['date']]


    # Update global sizes based on data
    INPUT_SIZE = len(all_features_for_Xt_input)
    EXTERNAL_VAR_SIZE = len(external_features)
    OUTPUT_DIM = len(target_feature_list)

    print(f"Input features (Xt) count: {INPUT_SIZE}")
    print(f"Selected External variable features (Ex) count: {EXTERNAL_VAR_SIZE}")
    print(f"Target features count: {OUTPUT_DIM}")


    # 2. Normalization (fit on full data before splitting for consistency)
    scaler_x = MinMaxScaler()
    df[all_features_for_Xt_input] = scaler_x.fit_transform(df[all_features_for_Xt_input])

    scaler_ex = MinMaxScaler()
    df[external_features] = scaler_ex.fit_transform(df[external_features])

    scaler_target = MinMaxScaler()
    df[target_feature_list] = scaler_target.fit_transform(df[target_feature_list])

    # Save scalers for later use in Gradio
    joblib.dump(scaler_x, SCALER_X_PATH)
    joblib.dump(scaler_ex, SCALER_EX_PATH)
    joblib.dump(scaler_target, SCALER_TARGET_PATH)
    print("Scalers saved.")

    # 3. Data Splitting (80% train, 10% val, 10% test)
    total_len = len(df)
    train_split = int(total_len * 0.8)
    val_split = int(total_len * 0.9)

    train_df = df.iloc[:train_split].copy()
    val_df = df.iloc[train_split:val_split].copy()
    test_df = df.iloc[val_split:].copy()

    print(f"Train samples: {len(train_df)}, Val samples: {len(val_df)}, Test samples: {len(test_df)}")

    # 4. Create Datasets and DataLoaders
    train_dataset = ETTDataset(train_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)
    val_dataset = ETTDataset(val_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)
    test_dataset = ETTDataset(test_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    print(f"Train dataset size: {len(train_dataset)}")
    print(f"Validation dataset size: {len(val_dataset)}")
    print(f"Test dataset size: {len(test_dataset)}")

    # ==============================================================================
    # 9. Model Initialization, Training, and Evaluation
    # ==============================================================================
    model = CustomRNNForPrediction(
        input_size=INPUT_SIZE,
        hidden_size=HIDDEN_SIZE,
        external_var_size=EXTERNAL_VAR_SIZE,
        output_dim=OUTPUT_DIM,
        pred_len=PREDICTION_LENGTH
    ).to(device)

    print(f"\nModel initialized:\n{model}")

    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    print("\n--- Starting Training ---")
    for epoch in range(NUM_EPOCHS):
        model.train()
        total_train_loss = 0

        for batch_idx, (inputs, external_vars, targets) in enumerate(train_loader):
            inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)

            optimizer.zero_grad()
            predictions = model(inputs, external_vars)
            loss = criterion(predictions, targets)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

        avg_train_loss = total_train_loss / len(train_loader)

        model.eval()
        total_val_loss = 0
        with torch.no_grad():
            for inputs, external_vars, targets in val_loader:
                inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)
                predictions = model(inputs, external_vars)
                loss = criterion(predictions, targets)
                total_val_loss += loss.item()

        avg_val_loss = total_val_loss / len(val_loader)

        print(f"Epoch {epoch+1}/{NUM_EPOCHS}, Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    print("Training finished!")

    # Save the trained model
    torch.save(model.state_dict(), MODEL_SAVE_PATH)
    print(f"Model saved to: {MODEL_SAVE_PATH}")


    print("\n--- Evaluating on Test Set ---")
    model.eval()
    test_loss = 0
    all_predictions_scaled = []
    all_targets_scaled = []
    all_inputs_for_plot_scaled = [] # To store the input sequences for plotting
    with torch.no_grad():
        for inputs, external_vars, targets in test_loader:
            inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)
            predictions = model(inputs, external_vars)
            loss = criterion(predictions, targets)
            test_loss += loss.item()

            all_predictions_scaled.append(predictions.cpu().numpy())
            all_targets_scaled.append(targets.cpu().numpy())
            all_inputs_for_plot_scaled.append(inputs.cpu().numpy()) # Store inputs for plotting

    avg_test_loss = test_loss / len(test_loader)
    print(f"Average Test Loss (MSE on scaled data): {avg_test_loss:.4f}")

    # Concatenate all batches of scaled data
    all_predictions_scaled_concat = np.concatenate(all_predictions_scaled, axis=0)
    all_targets_scaled_concat = np.concatenate(all_targets_scaled, axis=0)
    all_inputs_for_plot_scaled_concat = np.concatenate(all_inputs_for_plot_scaled, axis=0)

    # Inverse transform ALL predictions and targets for metric calculation and plotting
    all_predictions_original_scale = scaler_target.inverse_transform(
        all_predictions_scaled_concat.reshape(-1, OUTPUT_DIM)
    ).reshape(all_predictions_scaled_concat.shape)

    all_targets_original_scale = scaler_target.inverse_transform(
        all_targets_scaled_concat.reshape(-1, OUTPUT_DIM)
    ).reshape(all_targets_scaled_concat.shape)

    # Inverse transform input sequence for plotting (only the target feature if it's part of inputs)
    target_feature_idx_in_all_features_for_Xt_input = all_features_for_Xt_input.index(target_feature_list[0])
    all_inputs_target_feature_original_scale = scaler_x.inverse_transform(all_inputs_for_plot_scaled_concat.reshape(-1, INPUT_SIZE))
    all_inputs_target_feature_original_scale = all_inputs_target_feature_original_scale[:, target_feature_idx_in_all_features_for_Xt_input].reshape(all_inputs_for_plot_scaled_concat.shape[0], SEQUENCE_LENGTH)


    # ==============================================================================
    # 10. Evaluation Metrics (on original scale)
    # ==============================================================================
    print("\n--- Detailed Evaluation Metrics (on original scale) ---")
    metrics = calculate_metrics(all_targets_original_scale, all_predictions_original_scale)

    for metric_name, value in metrics.items():
        print(f"{metric_name}: {value:.4f}")

    # ==============================================================================
    # 11. Visualization: Comparing Ground Truth and Predicted Values
    # ==============================================================================
    print("\n--- Generating Visualization ---")

    num_samples_to_plot = 3 # You can change this to plot more/fewer samples
    fig, axes = plt.subplots(num_samples_to_plot, 1, figsize=(15, 5 * num_samples_to_plot))

    # Ensure axes is an array even for single plot
    if num_samples_to_plot == 1:
        axes = [axes]

    for i in range(num_samples_to_plot):
        ax = axes[i]
        sample_idx = np.random.randint(0, len(all_predictions_original_scale)) # Pick a random sample

        predicted_sample_orig_scale = all_predictions_original_scale[sample_idx]
        true_sample_orig_scale = all_targets_original_scale[sample_idx]
        input_sample_orig_scale = all_inputs_target_feature_original_scale[sample_idx]

        # Plotting
        time_points_input = np.arange(0, SEQUENCE_LENGTH)
        time_points_prediction = np.arange(SEQUENCE_LENGTH, SEQUENCE_LENGTH + PREDICTION_LENGTH)

        ax.plot(time_points_input, input_sample_orig_scale, label='Input Sequence (Ground Truth)', color='blue')
        ax.plot(time_points_prediction, true_sample_orig_scale[:, 0], label='Ground Truth (Future)', color='green', linestyle='--')
        ax.plot(time_points_prediction, predicted_sample_orig_scale[:, 0], label='Predicted (Future)', color='red', linestyle='-.')

        ax.set_title(f'Sample {sample_idx}: Ground Truth vs. Prediction for {target_feature_list[0]}')
        ax.set_xlabel('Time Steps')
        ax.set_ylabel(f'{target_feature_list[0]} (Original Scale)')
        ax.legend()
        ax.grid(True)

    plt.tight_layout()
    plt.show()

    print("Visualization complete.")

    # ==============================================================================
    # 12. Tabular Output: Predicted Values vs. Ground Truth
    # ==============================================================================
    print("\n--- Tabular Comparison of Predictions vs. Ground Truth ---")

    for i in range(min(3, len(all_predictions_original_scale))): # Display up to 3 random samples
        sample_idx = np.random.randint(0, len(all_predictions_original_scale))
        print(f"\n--- Sample {sample_idx} ---")

        predicted_values = all_predictions_original_scale[sample_idx]
        true_values = all_targets_original_scale[sample_idx]

        df_comparison = pd.DataFrame({
            'Time Step': np.arange(1, PREDICTION_LENGTH + 1),
            f'Ground Truth ({target_feature_list[0]})': true_values[:, 0],
            f'Predicted Value ({target_feature_list[0]})': predicted_values[:, 0]
        })
        print(df_comparison.to_string(index=False))

    print("\nTabular comparison complete.")

    # ==============================================================================
    # 13. Gradio Interface for Real-World Prediction
    # ==============================================================================
    print("\n--- Setting up Gradio Interface ---")

    # Ensure model and scalers are loaded for the Gradio interface
    # (This reloads them, useful if running the script multiple times without full restart)
    try:
        loaded_model = CustomRNNForPrediction(
            input_size=INPUT_SIZE,
            hidden_size=HIDDEN_SIZE,
            external_var_size=EXTERNAL_VAR_SIZE,
            output_dim=OUTPUT_DIM,
            pred_len=PREDICTION_LENGTH
        )
        loaded_model.load_state_dict(torch.load(MODEL_SAVE_PATH, map_location=device))
        loaded_model.to(device)
        loaded_model.eval() # Set to evaluation mode

        loaded_scaler_x = joblib.load(SCALER_X_PATH)
        loaded_scaler_ex = joblib.load(SCALER_EX_PATH)
        loaded_scaler_target = joblib.load(SCALER_TARGET_PATH)

        print("Model and scalers loaded successfully for Gradio.")

    except Exception as e:
        print(f"Error loading model or scalers for Gradio: {e}")
        print("Please ensure the model has been trained and saved successfully.")
        print("Gradio interface will not be launched.")
        loaded_model = None # Prevent Gradio from launching if loading fails


    if loaded_model:
        def predict_time_series(input_csv_file):
            """
            Predicts future time series values using the trained model from a CSV input.

            Args:
                input_csv_file (str): Path to a CSV file containing the last SEQUENCE_LENGTH
                                      data points, with columns matching the training data.

            Returns:
                pd.DataFrame: A DataFrame with the predicted values and metadata.
            """
            if input_csv_file is None:
                return "Please upload a CSV file."

            try:
                input_df = pd.read_csv(input_csv_file.name, parse_dates=['date'] if 'date' in pd.read_csv(input_csv_file.name).columns else False)
                print(f"Loaded input CSV with {len(input_df)} rows.")

                if len(input_df) < SEQUENCE_LENGTH:
                    return f"Error: Input CSV must contain at least {SEQUENCE_LENGTH} rows for prediction. Found {len(input_df)} rows."

                # Select the last SEQUENCE_LENGTH rows for prediction
                prediction_input_df = input_df.tail(SEQUENCE_LENGTH).copy()

                # Ensure columns are in the correct order as during training
                try:
                    input_x_data = prediction_input_df[all_features_for_Xt_input].values
                    input_ex_data = prediction_input_df[external_features].values
                except KeyError as k_err:
                    return f"Error: Missing expected column in input CSV: {k_err}. Ensure columns match training data ({all_features_for_Xt_input} and {external_features})."

                # Scale inputs using the loaded scalers
                input_x_scaled = loaded_scaler_x.transform(input_x_data)
                input_ex_scaled = loaded_scaler_ex.transform(input_ex_data)

                # Convert to torch tensors and add batch dimension
                input_x_tensor = torch.tensor(input_x_scaled, dtype=torch.float32).unsqueeze(0).to(device)
                input_ex_tensor = torch.tensor(input_ex_scaled, dtype=torch.float32).unsqueeze(0).to(device)

                # Make prediction
                with torch.no_grad():
                    predictions_scaled = loaded_model(input_x_tensor, input_ex_tensor)
                predictions_scaled = predictions_scaled.cpu().numpy() # Move to CPU and convert to numpy

                # Inverse transform predictions
                predictions_original_scale = loaded_scaler_target.inverse_transform(
                    predictions_scaled.reshape(-1, OUTPUT_DIM)
                ).reshape(predictions_scaled.shape)

                # Create output DataFrame
                prediction_df = pd.DataFrame({
                    'Time Step (Relative)': np.arange(1, PREDICTION_LENGTH + 1),
                    f'Predicted {target_feature_list[0]}': predictions_original_scale[0, :, 0] # Assuming single target
                })
                return prediction_df

            except Exception as e:
                return f"An error occurred during prediction: {e}. Please check your CSV format and data."

        # Gradio Interface
        iface = gr.Interface(
            fn=predict_time_series,
            inputs=gr.File(label=f"Upload CSV with last {SEQUENCE_LENGTH} data points"),
            outputs=gr.Dataframe(label=f"Predicted {target_feature_list[0]} for next {PREDICTION_LENGTH} steps"),
            title=f"Time Series Forecasting with Custom RNN ({target_feature_list[0]} Prediction)",
            description=(
                f"Upload a CSV file containing the last {SEQUENCE_LENGTH} historical time steps "
                f"of your data. The model will predict the next {PREDICTION_LENGTH} steps for '{target_feature_list[0]}'."
                f"<br><b>Required CSV columns (and order for Xt):</b> {all_features_for_Xt_input}"
                f"<br><b>Required CSV columns (for Ex):</b> {external_features}"
            ),
            allow_flagging='never' # Disable flagging for prediction tasks
        )

        print("\nGradio interface launching. Click the public URL to access.")
        iface.launch(share=True)
    else:
        print("Gradio interface not launched due to model/scaler loading errors.")