# -*- coding: utf-8 -*-
"""Time-GARN(For ICDE 2027).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdHaWgSLfr1boltXxVVVntKFMWfSiESd

Time-GARN | ICDE 2027
"""

# ==============================================================================
# 0. Initial Setup for Google Colab
# ==============================================================================
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error
from scipy.stats import pearsonr # For Pearson Correlation
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import joblib # For saving/loading scalers

# For Google Colab: Mount Google Drive to access your data
try:
    from google.colab import drive
    drive.mount('/content/drive')
    print("Google Drive mounted successfully.")
    BASE_PATH = ' ' # Your datasets path here
    os.makedirs(BASE_PATH, exist_ok=True)

    ETT_DATA_PATH = os.path.join(BASE_PATH, 'AQI Shanghai.csv') # AQI Shanghai for experiment example
    MODEL_SAVE_PATH = os.path.join(BASE_PATH, 'custom_rnn_model.pth')
    SCALER_X_PATH = os.path.join(BASE_PATH, 'scaler_x.pkl')
    SCALER_EX_PATH = os.path.join(BASE_PATH, 'scaler_ex.pkl')
    SCALER_TARGET_PATH = os.path.join(BASE_PATH, 'scaler_target.pkl')

    print(f"Project files will be saved/loaded from: {BASE_PATH}")

except ImportError:
    print("Not in Google Colab environment. Skipping Google Drive mount.")
    BASE_PATH = './'
    ETT_DATA_PATH = os.path.join(BASE_PATH, 'AQI Shanghai.csv') # AQI Shanghai for experiment example
    MODEL_SAVE_PATH = os.path.join(BASE_PATH, 'custom_rnn_model.pth')
    SCALER_X_PATH = os.path.join(BASE_PATH, 'scaler_x.pkl')
    SCALER_EX_PATH = os.path.join(BASE_PATH, 'scaler_ex.pkl')
    SCALER_TARGET_PATH = os.path.join(BASE_PATH, 'scaler_target.pkl')
    print(f"Project files will be saved/loaded from: {BASE_PATH}")

# Set device for training (GPU if available, else CPU)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# ==============================================================================
# 1. Configuration Parameters
# ==============================================================================
# --- Time Series Mode Options ---
FORECAST_MODE = 'multivariate' # Options: 'multivariate' or 'univariate'
TARGET_FEATURE = 'AQI'         # Choose any target feature column (e.g. 'AQI', 'OT', 'Close/Last')

# --- Time Series Specific Parameters ---
SEQUENCE_LENGTH = 30   # Number of past time steps to look at (seq_len)
PREDICTION_LENGTH = 60 # Number of future time steps to predict (pred_len)

# --- Feature Selection Parameters ---
FEATURE_SELECTION_METHOD = 'pearson' # Options: 'pearson'
NUM_EXTERNAL_FEATURES = 2            # Number of top external features to select

# --- Model Hyperparameters (These will be updated after data loading) ---
INPUT_SIZE = None       # Will be determined by the number of features in Xt
HIDDEN_SIZE = 64        # Dimension of the hidden state and cell state
EXTERNAL_VAR_SIZE = None # Will be determined by the number of features in Ex
OUTPUT_DIM = None       # Will be determined by the number of target features to predict

# --- Training Parameters ---
BATCH_SIZE = 32
NUM_EPOCHS = 50
LEARNING_RATE = 0.001

# ==============================================================================
# 2. Time-GARN | Custom Recurrent Cell Definition
# ==============================================================================
class CustomRecurrentCell(nn.Module):
    def __init__(self, input_size: int, hidden_size: int, external_var_size: int):
        super(CustomRecurrentCell, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.external_var_size = external_var_size

        # --- Parameters for Input Gate ---
        self.linear_x_to_it = nn.Linear(self.input_size, self.hidden_size)
        self.linear_h_to_it = nn.Linear(self.hidden_size, self.hidden_size)

        # --- Parameters for Ratio Gate ---
        self.linear_it_to_rt_numerator = nn.Linear(self.hidden_size, self.hidden_size)
        self.linear_ex_to_rt_denominator = nn.Linear(self.external_var_size, self.hidden_size)
        self.epsilon = 1e-8 # Small value for numerical stability in division

        # --- Parameters for Attention Gate ---
        self.query_transform = nn.Linear(self.hidden_size, self.hidden_size)
        self.key_transform = nn.Linear(self.external_var_size, self.hidden_size)
        self.value_transform = nn.Linear(self.external_var_size, self.hidden_size)

        # For scaled dot-product attention
        self.scale_factor = torch.sqrt(torch.tensor(self.hidden_size, dtype=torch.float32))

    def forward(self, x_t: torch.Tensor, h_prev: torch.Tensor, ex_t: torch.Tensor):
        # 1. Input Gate (It)
        it_output = torch.sigmoid(self.linear_x_to_it(x_t) + self.linear_h_to_it(h_prev))

        # 2. Ratio Gate (Rt)
        it_transformed = self.linear_it_to_rt_numerator(it_output)
        ex_transformed_for_ratio = self.linear_ex_to_rt_denominator(ex_t)

        numerator = it_transformed
        denominator = ex_transformed_for_ratio

        ratio_term = numerator / (denominator + self.epsilon)
        rt_output = torch.sigmoid(ratio_term)

        # 3. Attention Gate
        Q = self.query_transform(rt_output)
        K = self.key_transform(ex_t)
        V = self.value_transform(ex_t)

        # Scaled dot-product attention
        scores = torch.sum(Q * K, dim=1, keepdim=True) / self.scale_factor
        attention_weights = torch.softmax(scores, dim=1)

        best_ratio = attention_weights * V

        # 4. Final Output (New H_t)
        h_curr = best_ratio * self.value_transform(ex_t)

        return h_curr

# ==============================================================================
# 3. Time-GARN | Custom RNN Model for Prediction
# ==============================================================================
class CustomRNNForPrediction(nn.Module):
    def __init__(self, input_size, hidden_size, external_var_size, output_dim, pred_len):
        super().__init__()
        self.hidden_size = hidden_size
        self.pred_len = pred_len
        self.output_dim = output_dim

        self.cell = CustomRecurrentCell(input_size, hidden_size, external_var_size)

        # Output layer to map final hidden state to desired prediction horizon and dimensions
        self.prediction_layer = nn.Linear(self.hidden_size, self.pred_len * self.output_dim)

    def forward(self, inputs, external_vars, initial_h=None):
        batch_size, seq_len, _ = inputs.size()

        if initial_h is None:
            initial_h = torch.zeros(batch_size, self.hidden_size, device=inputs.device)

        h_curr = initial_h

        # Process the input sequence using custom cell
        for t in range(seq_len):
            x_t = inputs[:, t, :]
            ex_t = external_vars[:, t, :]
            h_curr = self.cell(x_t, h_curr, ex_t)

        # Predict future horizon
        predictions = self.prediction_layer(h_curr)
        predictions = predictions.view(batch_size, self.pred_len, self.output_dim)

        return predictions

# ==============================================================================
# 4. Dataset Class
# ==============================================================================
class ETTDataset(Dataset):
    def __init__(self, df, seq_len, pred_len, features_col, external_col, target_col):
        self.seq_len = seq_len
        self.pred_len = pred_len
        self.features_col = features_col
        self.external_col = external_col
        self.target_col = target_col

        self.data = df[features_col].values
        self.external_data = df[external_col].values if isinstance(external_col, list) else df[[external_col]].values
        self.target_data = df[target_col].values if isinstance(target_col, list) else df[[target_col]].values

        self.num_samples = len(self.data) - self.seq_len - self.pred_len + 1

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        input_seq = self.data[idx : idx + self.seq_len]
        external_seq_input = self.external_data[idx : idx + self.seq_len]
        target_seq = self.target_data[idx + self.seq_len : idx + self.seq_len + self.pred_len]

        return (
            torch.tensor(input_seq, dtype=torch.float32),
            torch.tensor(external_seq_input, dtype=torch.float32),
            torch.tensor(target_seq, dtype=torch.float32)
        )

# ==============================================================================
# 5. Feature Selection Function
# ==============================================================================
def select_external_features(df, target_col, all_features_except_target, method='pearson', num_features=1):
    if not isinstance(target_col, list):
        target_col_name = target_col
    else:
        target_col_name = target_col[0]
        print(f"Warning: Multiple target columns provided. Using '{target_col_name}' for feature selection.")

    candidate_df = df[all_features_except_target]
    target_series = df[target_col_name]

    if method == 'pearson':
        print(f"Selecting {num_features} external features using Pearson Correlation...")
        correlations = {}
        for feature in candidate_df.columns:
            corr, _ = pearsonr(candidate_df[feature], target_series)
            correlations[feature] = abs(corr)

        sorted_features = sorted(correlations.items(), key=lambda item: item[1], reverse=True)
        selected_features = [feature for feature, corr in sorted_features[:num_features]]
        print(f"Top {num_features} Pearson-correlated features: {selected_features}")
        return selected_features
    else:
        raise ValueError(f"Unknown feature selection method: {method}. Supported methods: ['pearson']")

# ==============================================================================
# 6. Metric Calculation Functions
# ==============================================================================
def calculate_metrics(y_true, y_pred, epsilon=1e-8):
    y_true_flat = y_true.flatten()
    y_pred_flat = y_pred.flatten()

    mse = mean_squared_error(y_true_flat, y_pred_flat)
    mae = mean_absolute_error(y_true_flat, y_pred_flat)

    sum_squared_error = np.sum((y_true_flat - y_pred_flat)**2)
    sum_squared_total = np.sum((y_true_flat - np.mean(y_true_flat))**2)
    rse = np.sqrt(sum_squared_error / (sum_squared_total + epsilon))

    mape = np.mean(np.abs((y_true_flat - y_pred_flat) / (y_true_flat + epsilon))) * 100

    corr_coeff, _ = pearsonr(y_true_flat, y_pred_flat)
    if np.isnan(corr_coeff):
        corr_coeff = 0.0

    return {
        'MSE': mse,
        'MAE': mae,
        'RSE': rse,
        'MAPE': mape,
        'CORR': corr_coeff
    }

# ==============================================================================
# 7. Main Execution Block
# ==============================================================================
if __name__ == "__main__":
    print("\n--- Starting Data Loading and Preprocessing ---")

    df = None
    try:
        df = pd.read_csv(ETT_DATA_PATH, parse_dates=['date'])
        print(f"Successfully loaded data from {ETT_DATA_PATH}")
    except FileNotFoundError:
        print(f"Dataset not found at {ETT_DATA_PATH}. Creating dummy dataframe for demonstration...")
        data = {
            'date': pd.to_datetime(pd.date_range(start='2020-01-01', periods=500, freq='H')),
            'HUFL': np.random.rand(500) * 50,
            'HULL': np.random.rand(500) * 60,
            'MUFL': np.random.rand(500) * 40,
            'MULL': np.random.rand(500) * 55,
            'LUFL': np.random.rand(500) * 30,
            'LULL': np.random.rand(500) * 45,
            'AQI': np.random.rand(500) * 100
        }
        df = pd.DataFrame(data)

    # --------------------------------------------------------------------------
    # 1. Target & Feature Selection based on FORECAST_MODE
    # --------------------------------------------------------------------------
    if FORECAST_MODE == 'univariate':
        print(f"\n[Mode: UNIVARIATE] Target Feature: '{TARGET_FEATURE}'")
        target_feature_list = [TARGET_FEATURE]
        all_features_for_Xt_input = [TARGET_FEATURE]
        external_features = [TARGET_FEATURE] # Self-referential input for univariate mode
    elif FORECAST_MODE == 'multivariate':
        print(f"\n[Mode: MULTIVARIATE] Primary Target Feature: '{TARGET_FEATURE}'")
        target_feature_list = [TARGET_FEATURE]

        all_candidate_features_for_Xt = [col for col in df.columns if col not in ['date'] + target_feature_list]

        external_features = select_external_features(
            df,
            target_col=target_feature_list,
            all_features_except_target=all_candidate_features_for_Xt,
            method=FEATURE_SELECTION_METHOD,
            num_features=NUM_EXTERNAL_FEATURES
        )

        all_features_for_Xt_input = [col for col in df.columns if col not in ['date']]
    else:
        raise ValueError(f"Invalid FORECAST_MODE: '{FORECAST_MODE}'. Choose 'univariate' or 'multivariate'.")

    INPUT_SIZE = len(all_features_for_Xt_input)
    EXTERNAL_VAR_SIZE = len(external_features)
    OUTPUT_DIM = len(target_feature_list)

    print(f"Input features (Xt) count: {INPUT_SIZE}")
    print(f"Selected External variable features (Ex) count: {EXTERNAL_VAR_SIZE}")
    print(f"Target features count: {OUTPUT_DIM}")

    # --------------------------------------------------------------------------
    # 2. Data Splitting
    # --------------------------------------------------------------------------
    total_len = len(df)
    train_split = int(total_len * 0.8)
    val_split = int(total_len * 0.9)

    train_df = df.iloc[:train_split].copy()
    val_df = df.iloc[train_split:val_split].copy()
    test_df = df.iloc[val_split:].copy()

    print(f"\nTrain samples: {len(train_df)}, Val samples: {len(val_df)}, Test samples: {len(test_df)}")

    # --------------------------------------------------------------------------
    # 3. Normalization (Fit on train set only to prevent data leakage)
    # --------------------------------------------------------------------------
    scaler_x = MinMaxScaler()
    train_df[all_features_for_Xt_input] = scaler_x.fit_transform(train_df[all_features_for_Xt_input])
    val_df[all_features_for_Xt_input] = scaler_x.transform(val_df[all_features_for_Xt_input])
    test_df[all_features_for_Xt_input] = scaler_x.transform(test_df[all_features_for_Xt_input])

    scaler_ex = MinMaxScaler()
    train_df[external_features] = scaler_ex.fit_transform(train_df[external_features])
    val_df[external_features] = scaler_ex.transform(val_df[external_features])
    test_df[external_features] = scaler_ex.transform(test_df[external_features])

    scaler_target = MinMaxScaler()
    train_df[target_feature_list] = scaler_target.fit_transform(train_df[target_feature_list])
    val_df[target_feature_list] = scaler_target.transform(val_df[target_feature_list])
    test_df[target_feature_list] = scaler_target.transform(test_df[target_feature_list])

    # Save scalers
    joblib.dump(scaler_x, SCALER_X_PATH)
    joblib.dump(scaler_ex, SCALER_EX_PATH)
    joblib.dump(scaler_target, SCALER_TARGET_PATH)
    print("Scalers fitted on train set and saved successfully.")

    # --------------------------------------------------------------------------
    # 4. Create Datasets and DataLoaders
    # --------------------------------------------------------------------------
    train_dataset = ETTDataset(train_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)
    val_dataset = ETTDataset(val_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)
    test_dataset = ETTDataset(test_df, SEQUENCE_LENGTH, PREDICTION_LENGTH, all_features_for_Xt_input, external_features, target_feature_list)

    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

    print(f"Train dataset size: {len(train_dataset)}")
    print(f"Validation dataset size: {len(val_dataset)}")
    print(f"Test dataset size: {len(test_dataset)}")

    # ==============================================================================
    # 8. Model Initialization, Training, and Evaluation
    # ==============================================================================
    model = CustomRNNForPrediction(
        input_size=INPUT_SIZE,
        hidden_size=HIDDEN_SIZE,
        external_var_size=EXTERNAL_VAR_SIZE,
        output_dim=OUTPUT_DIM,
        pred_len=PREDICTION_LENGTH
    ).to(device)

    print(f"\nModel initialized:\n{model}")

    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

    print("\n--- Starting Training ---")
    for epoch in range(NUM_EPOCHS):
        model.train()
        total_train_loss = 0

        for batch_idx, (inputs, external_vars, targets) in enumerate(train_loader):
            inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)

            optimizer.zero_grad()
            predictions = model(inputs, external_vars)
            loss = criterion(predictions, targets)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

        avg_train_loss = total_train_loss / len(train_loader)

        model.eval()
        total_val_loss = 0
        with torch.no_grad():
            for inputs, external_vars, targets in val_loader:
                inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)
                predictions = model(inputs, external_vars)
                loss = criterion(predictions, targets)
                total_val_loss += loss.item()

        avg_val_loss = total_val_loss / len(val_loader)

        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"Epoch {epoch+1}/{NUM_EPOCHS}, Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    print("Training finished!")

    # Save trained model
    torch.save(model.state_dict(), MODEL_SAVE_PATH)
    print(f"Model saved to: {MODEL_SAVE_PATH}")

    # --------------------------------------------------------------------------
    # Evaluation on Test Set
    # --------------------------------------------------------------------------
    print("\n--- Evaluating on Test Set ---")
    model.eval()
    test_loss = 0
    all_predictions_scaled = []
    all_targets_scaled = []
    all_inputs_for_plot_scaled = []

    with torch.no_grad():
        for inputs, external_vars, targets in test_loader:
            inputs, external_vars, targets = inputs.to(device), external_vars.to(device), targets.to(device)
            predictions = model(inputs, external_vars)
            loss = criterion(predictions, targets)
            test_loss += loss.item()

            all_predictions_scaled.append(predictions.cpu().numpy())
            all_targets_scaled.append(targets.cpu().numpy())
            all_inputs_for_plot_scaled.append(inputs.cpu().numpy())

    avg_test_loss = test_loss / len(test_loader)
    print(f"Average Test Loss (MSE on scaled data): {avg_test_loss:.4f}")

    all_predictions_scaled_concat = np.concatenate(all_predictions_scaled, axis=0)
    all_targets_scaled_concat = np.concatenate(all_targets_scaled, axis=0)
    all_inputs_for_plot_scaled_concat = np.concatenate(all_inputs_for_plot_scaled, axis=0)

    # Inverse transform predictions and targets
    all_predictions_original_scale = scaler_target.inverse_transform(
        all_predictions_scaled_concat.reshape(-1, OUTPUT_DIM)
    ).reshape(all_predictions_scaled_concat.shape)

    all_targets_original_scale = scaler_target.inverse_transform(
        all_targets_scaled_concat.reshape(-1, OUTPUT_DIM)
    ).reshape(all_targets_scaled_concat.shape)

    target_feature_idx_in_all_features_for_Xt_input = all_features_for_Xt_input.index(target_feature_list[0])
    all_inputs_target_feature_original_scale = scaler_x.inverse_transform(all_inputs_for_plot_scaled_concat.reshape(-1, INPUT_SIZE))
    all_inputs_target_feature_original_scale = all_inputs_target_feature_original_scale[:, target_feature_idx_in_all_features_for_Xt_input].reshape(all_inputs_for_plot_scaled_concat.shape[0], SEQUENCE_LENGTH)

    # --------------------------------------------------------------------------
    # Metrics
    # --------------------------------------------------------------------------
    print("\n--- Detailed Evaluation Metrics (on original scale) ---")
    metrics = calculate_metrics(all_targets_original_scale, all_predictions_original_scale)

    for metric_name, value in metrics.items():
        print(f"{metric_name}: {value:.4f}")

    # --------------------------------------------------------------------------
    # Visualization
    # --------------------------------------------------------------------------
    print("\n--- Generating Visualization ---")
    num_samples_to_plot = 3
    fig, axes = plt.subplots(num_samples_to_plot, 1, figsize=(15, 5 * num_samples_to_plot))

    if num_samples_to_plot == 1:
        axes = [axes]

    for i in range(num_samples_to_plot):
        ax = axes[i]
        sample_idx = np.random.randint(0, len(all_predictions_original_scale))

        predicted_sample_orig_scale = all_predictions_original_scale[sample_idx]
        true_sample_orig_scale = all_targets_original_scale[sample_idx]
        input_sample_orig_scale = all_inputs_target_feature_original_scale[sample_idx]

        time_points_input = np.arange(0, SEQUENCE_LENGTH)
        time_points_prediction = np.arange(SEQUENCE_LENGTH, SEQUENCE_LENGTH + PREDICTION_LENGTH)

        ax.plot(time_points_input, input_sample_orig_scale, label='Input Sequence (Ground Truth)', color='blue')
        ax.plot(time_points_prediction, true_sample_orig_scale[:, 0], label='Ground Truth (Future)', color='green', linestyle='--')
        ax.plot(time_points_prediction, predicted_sample_orig_scale[:, 0], label='Predicted (Future)', color='red', linestyle='-.')

        ax.set_title(f'Sample {sample_idx}: Ground Truth vs. Prediction for {target_feature_list[0]} ({FORECAST_MODE.capitalize()} Mode)')
        ax.set_xlabel('Time Steps')
        ax.set_ylabel(f'{target_feature_list[0]} (Original Scale)')
        ax.legend()
        ax.grid(True)

    plt.tight_layout()
    plt.show()

    # --------------------------------------------------------------------------
    # Tabular Output
    # --------------------------------------------------------------------------
    print("\n--- Tabular Comparison of Predictions vs. Ground Truth ---")
    for i in range(min(3, len(all_predictions_original_scale))):
        sample_idx = np.random.randint(0, len(all_predictions_original_scale))
        print(f"\n--- Sample {sample_idx} ---")

        predicted_values = all_predictions_original_scale[sample_idx]
        true_values = all_targets_original_scale[sample_idx]

        df_comparison = pd.DataFrame({
            'Time Step': np.arange(1, PREDICTION_LENGTH + 1),
            f'Ground Truth ({target_feature_list[0]})': true_values[:, 0],
            f'Predicted Value ({target_feature_list[0]})': predicted_values[:, 0]
        })
        print(df_comparison.to_string(index=False))

    print("\nScript execution complete.")